// Q-SHIELD ESP32 firmware, protocol v1 skeleton.
// STATUS: NOT COMPILED, NOT FLASHED, NOT TESTED. Written without a connected board.
//
// Does: Wi-Fi, HMAC-SHA256 device authentication (provisioned secret; symmetric, NOT
// post-quantum), register + heartbeat with a persisted monotonic counter.
// Does NOT: send telemetry. Telemetry carries a `tamper` flag and sensor values, and no
// pin mapping exists until the board is identified and wired. Reporting tamper=false
// without a real reed switch would be a false claim.
//
// Wire format and signing input: backend/protocol/envelope.py, test vector:
// tests/vectors/envelope_v1.json (verify HMAC output against it first).
#include <Arduino.h>
#include <WiFi.h>
#include <HTTPClient.h>
#include <Preferences.h>
#include "mbedtls/md.h"
#include "secrets.h"  // generated by scripts/enroll_device.py; gitignored

static const char *FW_VERSION = "esp32-0.1-skeleton";
static const uint32_t HEARTBEAT_MS = 5000;
static const uint32_t COUNTER_PERSIST_EVERY = 50;

static Preferences prefs;
static uint64_t counter = 0;
static bool registered = false;

static String hmacHex(const String &data) {
  uint8_t out[32];
  const mbedtls_md_info_t *info = mbedtls_md_info_from_type(MBEDTLS_MD_SHA256);
  mbedtls_md_hmac(info, DEVICE_SECRET, sizeof(DEVICE_SECRET),
                  (const unsigned char *)data.c_str(), data.length(), out);
  static const char *hex = "0123456789abcdef";
  String s;
  for (int i = 0; i < 32; i++) { s += hex[out[i] >> 4]; s += hex[out[i] & 15]; }
  return s;
}

// Reserve counters ahead of use so a crash/power loss can never reuse one.
static uint64_t nextCounter() {
  counter++;
  if (counter % COUNTER_PERSIST_EVERY == 0) prefs.putULong64("ctr", counter);
  return counter;
}

static String jsonEscape(const String &s) {
  String o;
  for (char c : s) { if (c == '"' || c == '\') o += '\'; o += c; }
  return o;
}

static bool send(const char *path, const char *type, const String &payload) {
  uint64_t c = nextCounter();
  String signingInput = String("QSHIELD-V1\nhmac-sha256-psk\n") + type + "\n" + DEVICE_ID + "\n" +
                        String((unsigned long long)c) + "\n" + payload;
  String body = String("{\"proto\":1,\"auth\":\"hmac-sha256-psk\",\"type\":\"") + type +
                "\",\"device_id\":\"" DEVICE_ID "\",\"counter\":" + String((unsigned long long)c) +
                ",\"payload\":\"" + jsonEscape(payload) + "\",\"tag\":\"" + hmacHex(signingInput) + "\"}";
  HTTPClient http;
  http.begin(String("http://") + GATEWAY_HOST + ":" + GATEWAY_PORT + "/api/v1/" + path);
  http.addHeader("Content-Type", "application/json");
  int code = http.POST(body);
  http.end();
  Serial.printf("%s -> %d\n", path, code);
  return code == 200;
}

void setup() {
  Serial.begin(115200);
  prefs.begin("qshield", false);
  // Skip past any counters used since the last persist.
  counter = prefs.getULong64("ctr", 0) + COUNTER_PERSIST_EVERY + 1;
  prefs.putULong64("ctr", counter);
  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
}

void loop() {
  static uint32_t last = 0;
  if (WiFi.status() != WL_CONNECTED) { delay(500); return; }
  if (!registered) {
    String p = String("{\"fw_version\":\"") + FW_VERSION + "\",\"hw\":\"esp32\",\"capabilities\":[]}";
    registered = send("register", "register", p);
    if (!registered) { delay(2000); return; }
  }
  if (millis() - last >= HEARTBEAT_MS) {
    last = millis();
    if (!send("heartbeat", "heartbeat", String("{\"uptime_ms\":") + millis() + "}")) registered = false;
  }
}
