"""Q-SHIELD integrated demonstration (Phase 11): one reproducible, end-to-end run on the REAL gateway.

    python scripts/demo_full.py                 # full story, no camera
    python scripts/demo_full.py --webcam        # also run the real webcam + YOLO11n pipeline (ML-KEM session)
    python scripts/demo_full.py --pace 2 --hold # pause 2 s between steps, keep the gateway up for the dashboard

A real FastAPI gateway is started on 127.0.0.1 (uvicorn, in-process thread) against a scratch database and scratch
keys. Every step goes over HTTP through the same code as production: HMAC device auth, ML-DSA-65 signature
verification, trust engine, quarantine enforcement, recovery orchestrator, ML-DSA-signed evidence chain.

Honesty labels printed by the demo:
  SIMULATED  device telemetry comes from the software agent (no ESP32); attacks are generated by attack_simulation/;
             visual violations after the webcam step are synthetic detections signed with the real vision key.
  TIME-LAPSE the trust ramp after remediation needs tens of minutes of clean evidence at the documented parameters;
             the demo advances the gateway clock (and says so) instead of waiting. No parameter is changed for the demo.
"""
from __future__ import annotations

import argparse
import os
import secrets
import sys
import tempfile
import threading
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import httpx  # noqa: E402
import uvicorn  # noqa: E402

from attack_simulation import AttackSimulator, SignerHandle  # noqa: E402
from backend.api.app import create_app  # noqa: E402
from backend.config import Settings  # noqa: E402
from backend.devices.store import Store  # noqa: E402
from backend.evidence.chain import EvidenceChain, EvidenceSigner  # noqa: E402
from backend.protocol.envelope import AUTH_HMAC  # noqa: E402
from backend.recovery.orchestrator import RecoveryOrchestrator  # noqa: E402
from backend.security.credentials import EncryptedCredentialStore  # noqa: E402
from backend.security.keystore import KIND_KEM, KIND_SIG, PqcKeyStore, kem_kek, signer_kek  # noqa: E402
from backend.security.pqc import get_backend  # noqa: E402
from backend.security.pqc_gateway import PqcGateway  # noqa: E402
from backend.trust.config import TrustConfig  # noqa: E402
from backend.trust.service import TrustService  # noqa: E402
from backend.twin.twin import DigitalTwin  # noqa: E402
from device_agent.agent import DeviceAgent  # noqa: E402

DEVICE = "DEVICE-001"
KNOWN_GOOD = {"fw_version": "agent-0.1", "cfg_hash": "cfg-good-1",
              "capabilities": ["tamper", "temperature", "vibration"], "sensor_ranges": {"temperature_c": [-20, 60]}}
REPORT_EVERY_S = 10            # simulated reporting period during recovery: inside the 15 s offline timeout,
                               # so the device never looks stale between reports (credit is the same per minute)

USE_COLOR = sys.stdout.isatty()
C = {"o": "\033[38;5;209m", "g": "\033[32m", "r": "\033[31m", "y": "\033[33m", "b": "\033[1m", "d": "\033[2m", "x": "\033[0m"}


def c(key: str, s: str) -> str:
    return f"{C[key]}{s}{C['x']}" if USE_COLOR else s


class DemoClock:
    """Wall clock plus an explicit, announced offset (TIME-LAPSE)."""

    def __init__(self):
        self.offset = 0.0
        self._lock = threading.Lock()

    def __call__(self) -> float:
        with self._lock:
            return time.time() + self.offset

    def fast_forward(self, s: float) -> None:
        with self._lock:
            self.offset += s


class Demo:
    def __init__(self, args):
        self.a, self.clock, self.step_no = args, DemoClock(), 0
        self.dir = Path(tempfile.mkdtemp(prefix="qshield-demo-"))

    # ------------------------------------------------------------------ output
    def step(self, title: str) -> None:
        self.step_no += 1
        if self.a.pace:
            time.sleep(self.a.pace)
        print()
        print(c("o", f"━━ STEP {self.step_no:02d} ") + c("b", title))

    def say(self, s: str) -> None:
        print(f"   {s}")

    def trust(self) -> dict:
        return self.op.get(f"/api/v1/trust/{DEVICE}").json()

    def show_trust(self, prefix: str = "") -> dict:
        t = self.trust()
        state = t.get("state", t.get("status"))
        colour = {"TRUSTED": "g", "SUSPICIOUS": "y", "QUARANTINED": "r"}.get(state, "o")
        caps = ", ".join(x["name"] for x in t.get("caps", [])) or "none"
        self.say(f"{prefix}TRUST {c('b', str(t.get('score', '--')).rjust(3))}  STATE {c(colour, state)}   caps: {caps}")
        return t

    def last_reason(self) -> None:
        h = self.op.get(f"/api/v1/trust/{DEVICE}/history", params={"limit": 1}).json()
        if h and h[0]["reasons"]:
            r = h[0]["reasons"][0]
            self.say(c("d", f"reason: {r['signal']} {r['impact']:+.1f} ({r.get('factor') or ''}) event {h[0]['event_id']}"))

    # ------------------------------------------------------------------ setup (scratch world)
    def setup(self) -> None:
        store = Store(str(self.dir / "q.db"))
        master = secrets.token_bytes(32)
        creds = EncryptedCredentialStore(store, master)
        self.secret = secrets.token_bytes(32)
        store.enroll_device(DEVICE, AUTH_HMAC, self.clock())
        creds.put(DEVICE, self.secret)

        self.backend = get_backend("ML-KEM-768", "ML-DSA-65")
        ks = PqcKeyStore(self.dir / "pqc")
        self.kem_rec = ks.create(self.backend, KIND_KEM, "gateway-kem-1", kem_kek(master, "gateway-kem-1"))
        vis = ks.create(self.backend, KIND_SIG, "vision-1", signer_kek(master, "vision-1"))
        store.add_signer("vision-1", vis.algorithm, vis.public_key, "usb_webcam", [DEVICE], self.clock())
        _, self.vision_sk = ks.load_private(self.backend, "vision-1", signer_kek(master, "vision-1"))
        ev = ks.create(self.backend, KIND_SIG, "gateway-evidence-1", signer_kek(master, "gateway-evidence-1"))
        _, ev_sk = ks.load_private(self.backend, "gateway-evidence-1", signer_kek(master, "gateway-evidence-1"))

        pqc = PqcGateway.from_keystore(store, self.backend, ks, master, ["gateway-kem-1"], clock=self.clock)
        twin = DigitalTwin(store)
        trust = TrustService(store, TrustConfig(), clock=self.clock, twin=twin)
        evidence = EvidenceChain(store, EvidenceSigner(self.backend, ev_sk, ev.public_key, "gateway-evidence-1"))
        recovery = RecoveryOrchestrator(store, trust, twin, clock=self.clock)
        self.trust_svc = trust
        self.op_token = secrets.token_urlsafe(24)
        app = create_app(Settings(db_path=str(self.dir / "q.db"), keys_dir=str(self.dir)), clock=self.clock, store=store,
                         creds=creds, operator_token=self.op_token, ingest_token=secrets.token_urlsafe(24), pqc=pqc,
                         trust=trust, twin=twin, evidence=evidence, recovery=recovery)

        self.url = f"http://127.0.0.1:{self.a.port}"
        self.server = uvicorn.Server(uvicorn.Config(app, host="127.0.0.1", port=self.a.port, log_level="warning"))
        threading.Thread(target=self.server.run, daemon=True).start()
        for _ in range(100):
            if self.server.started:
                break
            time.sleep(0.05)
        self.gw = httpx.Client(base_url=self.url, timeout=30)
        self.op = httpx.Client(base_url=self.url, timeout=30, headers={"Authorization": f"Bearer {self.op_token}"})
        self.agent = DeviceAgent(DEVICE, self.secret, self.gw)
        self.sim = AttackSimulator(self.gw, self.op, DEVICE, agent=self.agent,
                                   signer=SignerHandle(self.backend, self.vision_sk, "vision-1"), clock=self.clock)

    # ------------------------------------------------------------------ story
    def run(self) -> int:
        print(c("b", "Q-SHIELD — integrated demonstration"))
        print(c("d", "SIMULATED device data (software agent, not ESP32) · attacks from attack_simulation/ · "
                     "ESP32 path is HMAC-SHA256, not PQC"))
        self.setup()
        self.say(f"gateway {self.url}   scratch state {self.dir}")
        self.say(f"dashboard {self.url}/dashboard/#token={self.op_token}")

        self.step("Clean device joins: authenticated (HMAC-SHA256) and registered against its known-good digital twin")
        self.op.put(f"/api/v1/devices/{DEVICE}/twin/expected", json=KNOWN_GOOD)
        self.agent.cfg_hash = KNOWN_GOOD["cfg_hash"]
        self.say(f"register  -> HTTP {self.agent.register().status_code}")
        self.show_trust()

        self.step("Authenticated telemetry")
        for _ in range(3):
            r = self.agent.telemetry()
        self.say(f"telemetry -> HTTP {r.status_code}  (SIMULATED values)")
        tw = self.op.get(f"/api/v1/devices/{DEVICE}/twin").json()["comparison"]
        self.say(f"digital twin: {tw['overall']}  ({', '.join(f'{k}={v['status']}' for k, v in tw['fields'].items())})")
        self.show_trust()

        if self.a.webcam:
            self.step("Real webcam + YOLO11n, observations ML-DSA-65 signed inside an ML-KEM-768 session")
            try:
                self.webcam()
            except RuntimeError as e:          # no camera: say so, never fake the step
                self.say(c("r", f"webcam step NOT run: {e}"))
                self.say(c("d", "   check camera.source in the vision config (--vision-config): 0 is usually the built-in "
                                "camera, 1 the first USB camera; 'python -m ai.vision probe --config <file>' tests it"))
            self.show_trust()
        else:
            self.step("Signed vision observation (webcam step skipped: run with --webcam for the real camera)")

        self.step("Attack 1: forged observation (payload altered, original ML-DSA signature kept)")
        res = self.sim.forge()
        self.say(f"gateway -> HTTP {res.http_status[0]}  {c('g', 'REJECTED') if res.detected else c('r', 'NOT DETECTED')}")
        self.show_trust()

        self.step("Attack 2: replay of a valid signed observation")
        res = self.sim.replay()
        self.say(f"original -> HTTP {res.http_status[0]}, replay -> HTTP {res.http_status[1]}  "
                 f"{c('g', 'REJECTED') if res.detected else c('r', 'NOT DETECTED')}")
        self.show_trust()
        self.say(c("d", "forged traffic only adds bounded pressure (<= 25): it can never quarantine a device by itself"))

        self.step("Compromised device reports its enclosure tamper switch OPEN (authentic message, abnormal content)")
        res = self.sim.tamper()
        self.show_trust()
        self.last_reason()

        self.step("Corroborating evidence: signed visual rule violation within the correlation window")
        res = self.sim.visual_violation(0.9)
        t = self.show_trust()
        if t.get("incident"):
            self.say(f"incident {t['incident']['id']}: {t['incident']['class']} ({' + '.join(t['incident']['modalities'])})")

        self.step("Quarantine is ENFORCED at the gateway")
        res = self.sim.quarantine_bypass()
        self.say(f"device normal telemetry -> HTTP {res.http_status[0]}   forged 'all clear' -> HTTP {res.http_status[1]}")
        acc = self.op.get(f"/api/v1/devices/{DEVICE}/access").json()
        self.say(f"access: normal={'allowed' if acc['normal']['allowed'] else c('r', 'BLOCKED')}  "
                 f"recovery channel={'open' if acc['recovery']['allowed'] else 'closed'}")
        self.show_trust()

        self.step("Forensic evidence chain (SHA-256 linked, ML-DSA-65 signed)")
        self.show_chain()

        self.step("Recovery started by the operator (security control channel)")
        self.agent.cfg_hash = None          # compromised configuration: the device can no longer vouch for it
        r = self.op.post(f"/api/v1/devices/{DEVICE}/recovery/start",
                         json={"reason": "incident contained; restore known-good configuration"}).json()
        self.say(f"{r['recovery_id']}  stage={r['stage']}  command={r['command']['action']} -> cfg {r['command']['cfg_hash']}")
        self.show_trust()

        self.step("Remediation -> health checks -> digital state verification")
        return self.recover()

    def webcam(self) -> None:
        from ai.vision.config import load_config

        cfg = load_config(self.a.vision_config)
        m, cam = cfg.model, cfg.camera
        # The device keeps operating while the vision service works: without its regular authenticated reports the
        # trust engine would (rightly) mark it stale during the model load, camera warm-up and capture.
        stop = threading.Event()

        def keep_reporting():
            while not stop.wait(4):
                try:
                    self.agent.telemetry()
                except httpx.TransportError:
                    pass
        reporter = threading.Thread(target=keep_reporting, name="demo-device-reports", daemon=True)
        reporter.start()
        try:
            self._webcam_run(cfg, m, cam)
        finally:
            stop.set()
            reporter.join(10)

    def _webcam_run(self, cfg, m, cam) -> None:
        from ai.vision.camera import OpenCVSource, warm_up
        from ai.vision.detector import YoloDetector
        from ai.vision.pipeline import VisionPipeline
        from ai.vision.runner import run
        from ai.vision.signed_sink import SignedHttpSink
        from datetime import datetime, timezone

        det = YoloDetector(m.path, m.name, m.conf_threshold, m.imgsz, m.device, m.classes_of_interest)
        src = OpenCVSource(cam.source, cam.backend, cam.width, cam.height)
        sink = SignedHttpSink(self.url, self.backend, "vision-1", "usb_webcam:0", self.vision_sk, secure=True,
                              gateway_key_id=self.kem_rec.key_id, gateway_public_key=self.kem_rec.public_key,
                              now=lambda: datetime.fromtimestamp(self.clock(), timezone.utc))
        listing = lambda: self.op.get("/api/v1/observations", params={"device_id": DEVICE, "limit": 500}).json()  # noqa: E731
        before = len(listing())
        try:
            if isinstance(cam.source, int):              # discard auto-exposure frames (they read as a covered lens)
                warm_up(src, cam.warmup_frames)
            n = run(VisionPipeline(cfg, det), src, sink, cam.target_fps, self.a.frames)
        finally:
            src.release()
        after = listing()
        obs = after[: max(0, len(after) - before)]          # newest first
        visual = [o for o in obs if o.get("event_type") == "visual_observation"]
        rules = [o for o in visual if o.get("anomaly")]
        health = [o for o in obs if o.get("event_type") == "camera_health"]
        self.say(f"{n} frames processed (after a {cam.warmup_frames if isinstance(cam.source, int) else 0}-frame camera warm-up), "
                 f"{len(obs)} signed observations accepted over the ML-KEM session: {len(visual) - len(rules)} clear, "
                 f"{len(rules)} restricted-zone rule match(es), {len(health)} camera-health report(s)")
        if rules:
            self.say(c("y", "   REAL detection: the camera saw a person in the restricted zone (right half of the frame). That is "
                            "genuine evidence, so trust drops now and it can correlate with other evidence inside the 60 s window. "
                            "Keep that half of the view clear during this step for the scripted story."))
        st = sink.status()
        if st["rejected"] or st["queued"] or st["last_error"]:   # say why observations are missing, if they are
            self.say(c("y", f"   transport: {st['sessions_established']} ML-KEM session(s), {st['delivered']} delivered, "
                            f"{st['rejected']} refused, {st['queued']} still queued; last error: {st['last_error']}"))
        for o in obs[:4]:
            if o.get("event_type") == "camera_health":       # by protocol: no object/confidence, only details.state
                self.say(c("d", f"  camera health: {(o.get('details') or {}).get('state')} auth={o.get('auth', '')[:18]}"))
                continue
            self.say(c("d", f"  {o.get('object')} conf {o.get('confidence') or 0:.2f} rule_violation={o.get('anomaly')} "
                            f"auth={o.get('auth', '')[:18]}"))

    def show_chain(self) -> None:
        v = self.op.get("/api/v1/evidence/verify").json()
        ok = c("g", "VERIFIED") if v["ok"] else c("r", f"BROKEN at {v['first_bad_seq']}: {v['reason']}")
        self.say(f"chain {ok}  entries={v['count']}  signed={'ML-DSA-65' if v['signed'] else 'NO'}  "
                 f"head={v['head_hash'][:16]}…")
        for e in self.op.get(f"/api/v1/evidence/device/{DEVICE}").json()[-3:]:
            self.say(c("d", f"  #{e['seq']:<3} {e['event_type']:<24} {e['event_hash'][:12]}… prev {e['prev_hash'][:12]}…"))

    def recover(self) -> int:
        rec = lambda: self.op.get(f"/api/v1/devices/{DEVICE}/recovery").json()["current"]  # noqa: E731
        stage = None
        stage_seen = None
        channel_open = True
        for i in range(2000):
            self.clock.fast_forward(REPORT_EVERY_S)
            resp = self.agent.recovery_report() if channel_open else self.agent.telemetry()
            r = rec()
            channel_open = r["stage"] in ("remediation_pending", "health_checks", "trust_ramp")
            if os.environ.get("QSHIELD_DEMO_DEBUG") and i % 30 == 0:
                d = self.trust_svc.engine.devices[DEVICE]
                print(f"DBG i={i} credit={d.credit_clock:.0f} score={d.score} lastviol_ago={self.clock()-(d.last_violation_ts or 0):.0f} "
                      f"last_ts_ahead={d.last_ts-self.clock():.1f} pen={ {k: round(v) for k, v in d.penalties.items() if v > .5} } "
                      f"q={d.pressure:.1f} dup={d.duplicates}")
            if r["stage"] != stage or r["status"] != "active":
                stage = r["stage"]
                t = self.trust()
                self.say(f"[{(i + 1) * REPORT_EVERY_S // 60:>3} min, {c('y', 'TIME-LAPSE')}] stage={c('b', r['status'] if r['status'] != 'active' else stage):<22} "
                         f"state={t['state']:<11} score={t['score']:>3}  ({'recovery' if channel_open else 'normal'} channel HTTP {resp.status_code})")
                if stage == "health_checks":
                    tw = self.op.get(f"/api/v1/devices/{DEVICE}/twin").json()["comparison"]
                    self.say(c("d", f"   remediation acknowledged; twin now {tw['overall']}"))
                if stage == "trust_ramp":
                    checks = " ".join("✔" if h["clean"] else "✖" for h in r["health"][-3:])
                    self.say(c("d", f"   health checks {checks} -> VERIFIED; trust must still be rebuilt from evidence"))
                if stage == "restoring" and r["status"] == "active":
                    self.say(c("g", "   ACCESS RESTORED (RECOVERED): device back on the normal channel"))
            if r["status"] in ("completed", "failed"):
                break
            if self.a.pace:
                # Presentation pacing (wall clock only; the gateway's TIME-LAPSE is unchanged): hold each health check
                # and each stage change long enough for the dashboard (2 s refresh) to show it.
                if r["stage"] != stage_seen:
                    time.sleep(self.a.pace)
                elif r["stage"] in ("remediation_pending", "health_checks"):
                    time.sleep(min(self.a.pace, 2.5))
            stage_seen = r["stage"]
        self.step("Result")
        self.show_trust()
        r = rec()
        if r["status"] != "completed":
            self.say(c("r", f"recovery {r['status']}: {r.get('failure_reason')}"))
        hist = self.op.get(f"/api/v1/trust/{DEVICE}/history", params={"limit": 500}).json()
        path = [h["new_state"] for h in reversed(hist) if h["previous_state"] != h["new_state"]]
        self.say("state path: " + " → ".join(path))
        self.show_chain()
        self.say(f"dashboard {self.url}/dashboard/#token={self.op_token}")
        if self.a.hold:
            self.say("gateway kept running for the dashboard; the simulated device keeps reporting every 4 s; Ctrl+C to stop")
            try:
                while True:
                    time.sleep(4)                     # < uvicorn's 5 s keep-alive, so the pooled connection stays valid
                    try:
                        self.agent.telemetry()        # real time from here on: no more time-lapse
                    except httpx.TransportError:      # server closed an idle connection: the next report reconnects
                        pass
            except KeyboardInterrupt:
                pass
        self.server.should_exit = True
        return 0 if r["status"] == "completed" else 1


def main() -> int:
    for stream in (sys.stdout, sys.stderr):          # Windows consoles default to cp1252
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--port", type=int, default=8765)
    ap.add_argument("--webcam", action="store_true", help="run the real webcam + YOLO11n pipeline step")
    ap.add_argument("--vision-config", default="config/vision.json")
    ap.add_argument("--frames", type=int, default=40, help="webcam frames to process")
    ap.add_argument("--pace", type=float, default=0.0, help="seconds to pause before each step")
    ap.add_argument("--hold", action="store_true", help="keep the gateway running at the end (dashboard)")
    return Demo(ap.parse_args()).run()


if __name__ == "__main__":
    sys.exit(main())
