"""Enroll a device: create its provisioned HMAC-SHA256 secret and register it with the gateway.

    python scripts/enroll_device.py DEVICE-001 [--esp32-secrets hardware/esp32/firmware/include/secrets.h]

The secret (32 random bytes) is stored encrypted in the gateway DB (master key:
keys/master.key), written once to keys/devices/<id>.secret (gitignored, plaintext, for the
device/agent to use) and, if requested, into a gitignored secrets.h for the firmware. It is
never printed. This credential is symmetric; it is not post-quantum.
"""
import argparse
import secrets
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from backend.config import Settings  # noqa: E402
from backend.devices.store import Store  # noqa: E402
from backend.protocol.envelope import AUTH_HMAC, SECRET_BYTES  # noqa: E402
from backend.security.credentials import (  # noqa: E402
    EncryptedCredentialStore, load_or_create_master_key,
)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("device_id")
    ap.add_argument("--esp32-secrets", help="also write firmware secrets.h to this path")
    ap.add_argument("--wifi-ssid", default="CHANGE_ME")
    ap.add_argument("--wifi-password", default="CHANGE_ME")
    ap.add_argument("--gateway-host", default="CHANGE_ME", help="hostname or IP of the laptop gateway")
    ap.add_argument("--gateway-port", type=int, default=8000)
    a = ap.parse_args()

    settings = Settings.load()
    secret = secrets.token_bytes(SECRET_BYTES)
    store = Store(settings.db_path)
    creds = EncryptedCredentialStore(store, load_or_create_master_key(settings.keys_dir, settings.master_key_hex))
    if store.get_device(a.device_id) is not None:
        print(f"error: {a.device_id} is already enrolled", file=sys.stderr)
        return 1
    store.enroll_device(a.device_id, AUTH_HMAC, time.time())
    creds.put(a.device_id, secret)  # encrypted at rest under the master key

    keyfile = Path(settings.keys_dir) / "devices" / f"{a.device_id}.secret"
    keyfile.parent.mkdir(parents=True, exist_ok=True)
    keyfile.write_text(secret.hex() + "\n")
    print(f"enrolled {a.device_id}; device secret written to {keyfile}")

    if a.esp32_secrets:
        out = Path(a.esp32_secrets)
        out.parent.mkdir(parents=True, exist_ok=True)
        arr = ", ".join(f"0x{b:02x}" for b in secret)
        out.write_text(
            "// Generated by scripts/enroll_device.py. Gitignored. Do not commit.\n"
            "#pragma once\n"
            f'#define WIFI_SSID "{a.wifi_ssid}"\n'
            f'#define WIFI_PASSWORD "{a.wifi_password}"\n'
            f'#define GATEWAY_HOST "{a.gateway_host}"\n'
            f"#define GATEWAY_PORT {a.gateway_port}\n"
            f'#define DEVICE_ID "{a.device_id}"\n'
            f"static const unsigned char DEVICE_SECRET[{SECRET_BYTES}] = {{{arr}}};\n"
        )
        print(f"wrote firmware credentials to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
