"""Write tests/vectors/envelope_v1_cases.json: device-protocol test vectors for firmware authors.

Every case is produced by the gateway's own reference implementation (backend/protocol/envelope.py) with a TEST key,
in the order a freshly flashed ESP32 would send them. Firmware that reproduces `signing_input_hex`, `tag` and
`envelope_json` byte for byte speaks the protocol; tests/security/test_device_vectors.py checks that the file still
matches the implementation and that a gateway accepts every envelope in order.

    python scripts/make_device_vectors.py           # rewrite the file
    python scripts/make_device_vectors.py --check   # exit 1 if the file is out of date
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from backend.protocol.envelope import AUTH_HMAC, PROTO_VERSION, build_hmac_envelope, signing_input  # noqa: E402

OUT = Path(__file__).resolve().parents[1] / "tests" / "vectors" / "envelope_v1_cases.json"
TEST_SECRET = bytes(range(32))           # TEST KEY ONLY (the same key as tests/vectors/envelope_v1.json)
DEVICE = "DEVICE-001"
FW = "esp32-0.1-skeleton"

# (name, message type, counter, payload object or raw payload text, what it exercises)
CASES = [
    ("register", "register", 52, {"fw_version": FW, "hw": "esp32", "capabilities": ["tamper"]},
     "first message after a fresh flash: the firmware starts at stored counter 0 + 50 + 1 and increments before use"),
    ("heartbeat", "heartbeat", 53, {"uptime_ms": 5000}, "liveness"),
    ("telemetry_minimal", "telemetry", 54, {"tamper": False, "fw_version": FW, "rssi_dbm": -61},
     "only the reed switch wired: absent sensors are left out, never sent as 0"),
    ("telemetry_tamper_open", "telemetry", 55, {"tamper": True, "fw_version": FW, "rssi_dbm": -61},
     "enclosure open: the gateway applies the physical_tamper signal"),
    ("telemetry_all_sensors", "telemetry", 56,
     {"temperature_c": 24.5, "humidity_pct": 41.2, "pressure_hpa": 1008.6, "vibration_g": 0.03, "rssi_dbm": -58,
      "tamper": False, "fw_version": FW, "cfg_hash": "cfg-good-1"},
     "BME280 + MPU6050 + reed switch + Wi-Fi RSSI + firmware and configuration identity"),
    ("register_escaped_text", "register", 57,
     '{"fw_version":"esp32-0.1 \\"lab\\\\build\\"","hw":"esp32","capabilities":[]}',
     "a payload containing a quote and a backslash: envelope_json shows how the payload string must be escaped"),
    ("heartbeat_max_counter", "heartbeat", 2 ** 53, {"uptime_ms": 10000},
     "largest counter the gateway accepts (2^53); a device must be re-provisioned before reaching it"),
]


def payload_text(p) -> str:
    return p if isinstance(p, str) else json.dumps(p, separators=(",", ":"))


def build() -> dict:
    cases = []
    for name, mtype, counter, payload, note in CASES:
        text = payload_text(payload)
        env = build_hmac_envelope(TEST_SECRET, mtype, DEVICE, counter, text)
        ordered = {k: env[k] for k in ("proto", "auth", "type", "device_id", "counter", "payload", "tag")}
        cases.append({
            "name": name, "note": note, "type": mtype, "counter": counter, "payload": text,
            "signing_input_hex": signing_input(AUTH_HMAC, mtype, DEVICE, counter, text).hex(),
            "tag": env["tag"], "envelope_json": json.dumps(ordered, separators=(",", ":")),
        })
    return {
        "description": "Q-SHIELD device protocol v1 test vectors, in sending order. TEST KEY ONLY, never a real secret. "
                       "Generated by scripts/make_device_vectors.py from backend/protocol/envelope.py.",
        "proto": PROTO_VERSION, "auth": AUTH_HMAC, "device_id": DEVICE, "secret_hex": TEST_SECRET.hex(),
        "signing_input": "'QSHIELD-V1' LF auth LF type LF device_id LF decimal(counter) LF payload (UTF-8, exact bytes)",
        "cases": cases,
    }


def main() -> int:
    text = json.dumps(build(), indent=2) + "\n"
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT} is out of date: run python scripts/make_device_vectors.py")
            return 1
        print("vectors up to date")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(CASES)} cases)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
