"""Attack simulator: drives SYNTHETIC attacks through the REAL gateway and reports what the system actually did.

Simulation boundary (read before quoting any result):
  * every attack here is generated by this module, not observed in the wild;
  * attacks that need the device credential (tamper, sensor anomaly, config mismatch, malformed payload) model a
    COMPROMISED or PHYSICALLY TAMPERED device that still holds its key: the credential is valid, the content is not;
  * "visual violation" attacks send a synthetic detection signed with the vision service's real ML-DSA key; no camera
    frame is involved. They model a real detection event, or a compromised vision service;
  * nothing is asserted by the simulator: expected_detection is what the specification says should happen,
    actual_detection is read back from the gateway's own security events and trust records after the attack.

The simulator talks HTTP only (starlette TestClient or httpx.Client), so it exercises the same code path as a live
gateway. `gateway` needs no credentials; `operator` must carry the operator bearer token (used only to read results).
"""
from __future__ import annotations

import json
import secrets
import time
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Callable

from backend.protocol.envelope import MSG_TELEMETRY, build_hmac_envelope
from backend.protocol.observation import Observation
from backend.protocol.signed_observation import iso_utc, sign_observation

SIM_NOTE = "SIMULATED attack traffic generated by attack_simulation/; results are read back from the real gateway"


@dataclass
class SignerHandle:
    """The vision service's ML-DSA identity, used to produce validly signed synthetic observations."""
    backend: object
    secret_key: bytes
    signer_id: str
    source_id: str = "usb_webcam:0"


@dataclass
class AttackResult:
    attack_id: str
    attack_type: str
    target_device: str
    timestamp: float
    payload: dict
    expected_detection: str
    actual_detection: list
    http_status: list
    trust_effect: dict
    state_effect: dict
    evidence_id: str | None
    detected: bool
    simulated: bool = True
    note: str = SIM_NOTE
    extra: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return asdict(self)


class AttackSimulator:
    def __init__(self, gateway, operator, device_id: str, *, agent=None, signer: SignerHandle | None = None,
                 clock: Callable[[], float] = time.time):
        """agent: the device's DeviceAgent (shares its counter) — required for credentialed attacks."""
        self.gw, self.op, self.device_id = gateway, operator, device_id
        self.agent, self.signer, self.clock = agent, signer, clock
        self.results: list[AttackResult] = []

    # ------------------------------------------------------------------ observation of effects (operator API)
    def _trust(self) -> dict:
        r = self.op.get(f"/api/v1/trust/{self.device_id}")
        return r.json() if r.status_code == 200 else {}

    def _last_event_id(self) -> int:
        ev = self.op.get("/api/v1/events", params={"limit": 1}).json()
        return ev[0]["id"] if ev else 0

    def _events_since(self, last_id: int) -> list:
        ev = self.op.get("/api/v1/events", params={"limit": 500}).json()
        return [e for e in reversed(ev) if e["id"] > last_id]

    def _evidence_head(self) -> int:
        r = self.op.get("/api/v1/evidence/verify")
        return r.json()["head"]["seq"] if r.status_code == 200 else -1

    def _evidence_since(self, seq: int) -> list:
        if seq < 0:
            return []
        r = self.op.get("/api/v1/evidence", params={"after_seq": seq, "limit": 500})
        return r.json() if r.status_code == 200 else []

    def _run(self, attack_type: str, expected: str, action: Callable[[], tuple[list, dict]],
             detect: Callable[[list, dict, dict], bool], target: str | None = None) -> AttackResult:
        target = target or self.device_id
        before, ev0, seq0 = self._trust(), self._last_event_id(), self._evidence_head()
        ts = self.clock()
        statuses, payload = action()
        after = self._trust()
        events = self._events_since(ev0)
        evidence = [e for e in self._evidence_since(seq0) if e.get("device_id") == target]
        actual = [{"event_type": e["event_type"], "severity": e["severity"], "device_id": e["device_id"]} for e in events]
        res = AttackResult(
            attack_id=f"ATK-{uuid.uuid4().hex[:10]}", attack_type=attack_type, target_device=target, timestamp=ts,
            payload=payload, expected_detection=expected, actual_detection=actual, http_status=statuses,
            trust_effect={"before": before.get("score"), "after": after.get("score"),
                          "delta": (after.get("score") - before.get("score"))
                          if isinstance(after.get("score"), int) and isinstance(before.get("score"), int) else None,
                          "pressure_after": after.get("pressure"),
                          "caps_after": [c["name"] for c in after.get("caps", [])]},
            state_effect={"before": before.get("state"), "after": after.get("state")},
            evidence_id=evidence[-1]["event_id"] if evidence else None, detected=False)
        res.detected = bool(detect(events, before, after))
        self.results.append(res)
        return res

    # ------------------------------------------------------------------ builders
    def _obs(self, *, anomaly: bool, confidence: float = 0.9, obj: str = "person", device_id: str | None = None) -> Observation:
        now = datetime.fromtimestamp(self.clock(), timezone.utc)
        return Observation(event_type="visual_observation", device_id=device_id or self.device_id, timestamp=iso_utc(now),
                           source="usb_webcam", object=obj, confidence=confidence, zone="restricted_zone",
                           zone_kind="restricted", bbox={"x1": 0.55, "y1": 0.1, "x2": 0.9, "y2": 0.95}, anomaly=anomaly,
                           anomaly_reason="restricted_class_in_restricted_zone" if anomaly else None,
                           model={"name": "synthetic", "version": "attack-sim"},
                           details={"simulated": True})

    def _signed(self, obs: Observation) -> dict:
        if self.signer is None:
            raise RuntimeError("this attack needs a SignerHandle (vision-service ML-DSA key)")
        s = self.signer
        return sign_observation(s.backend, s.secret_key, s.signer_id, s.source_id, obs,
                                datetime.fromtimestamp(self.clock(), timezone.utc))

    def _need_agent(self):
        if self.agent is None:
            raise RuntimeError("credentialed attacks need the device agent (models a compromised/tampered device)")
        return self.agent

    @staticmethod
    def _has(events: list, *types: str) -> bool:
        return any(e["event_type"] in types for e in events)

    # ------------------------------------------------------------------ attacks
    def forge(self) -> AttackResult:
        """Tamper with a validly signed observation (hide an anomaly) and resend it with the original signature."""
        def act():
            env = self._signed(self._obs(anomaly=True))
            body = json.loads(env["payload"])
            body["anomaly"], body["anomaly_reason"] = False, None
            env["payload"] = json.dumps(body, sort_keys=True)
            r = self.gw.post("/api/v1/observations/signed", json=env)
            return [r.status_code], {"altered_field": "anomaly", "observation_id": env["observation_id"]}
        return self._run("forged_signature", "HTTP 401; pqc_invalid_signature; bounded pressure (<=25) on the target",
                         act, lambda ev, b, a: self._has(ev, "pqc_invalid_signature"))

    def replay(self) -> AttackResult:
        """Capture a valid signed observation and send it again."""
        def act():
            env = self._signed(self._obs(anomaly=False, confidence=0.8, obj="chair"))
            r1 = self.gw.post("/api/v1/observations/signed", json=env)
            r2 = self.gw.post("/api/v1/observations/signed", json=env)
            return [r1.status_code, r2.status_code], {"observation_id": env["observation_id"]}
        return self._run("replay", "first copy 200, replay 409; pqc_observation_replay; bounded pressure", act,
                         lambda ev, b, a: self._has(ev, "pqc_observation_replay"))

    def malformed(self) -> AttackResult:
        """Validly authenticated envelope whose payload fails the schema (compromised device firmware)."""
        agent = self._need_agent()

        def act():
            agent.counter += 1
            env = build_hmac_envelope(agent._secret, MSG_TELEMETRY, self.device_id, agent.counter,
                                      json.dumps({"temperature_c": "hot", "unexpected": True}))
            r = self.gw.post("/api/v1/telemetry", json=env)
            return [r.status_code], {"payload": "schema-invalid telemetry"}
        return self._run("malformed_packet", "HTTP 422; malformed_payload; identity factor penalty (authenticated sender)",
                         act, lambda ev, b, a: self._has(ev, "malformed_payload"))

    def auth_violation(self, attempts: int = 5) -> AttackResult:
        """Messages claiming to be the device but tagged with a wrong key."""
        def act():
            wrong = secrets.token_bytes(32)
            out = []
            for i in range(attempts):
                env = build_hmac_envelope(wrong, MSG_TELEMETRY, self.device_id, 10**12 + i,
                                          json.dumps({"tamper": True}))
                out.append(self.gw.post("/api/v1/telemetry", json=env).status_code)
            return out, {"attempts": attempts, "claimed_tamper": True}
        return self._run("authentication_violation", "HTTP 401 each; invalid_tag; pressure capped at 25 -> never QUARANTINED; "
                         "the forged tamper claim is never believed", act, lambda ev, b, a: self._has(ev, "invalid_tag"))

    def rogue_device(self) -> AttackResult:
        """An unenrolled device announcing itself."""
        rogue = f"ROGUE-{secrets.token_hex(3).upper()}"

        def act():
            env = build_hmac_envelope(secrets.token_bytes(32), MSG_TELEMETRY, rogue, 1, json.dumps({"tamper": False}))
            return [self.gw.post("/api/v1/telemetry", json=env).status_code], {"rogue_device_id": rogue}
        return self._run("rogue_device", "HTTP 401; unknown_device; unattributed (no trust record created, enrolled "
                         "devices unaffected)", act, lambda ev, b, a: self._has(ev, "unknown_device"))

    def sensor_anomaly(self, field_name: str = "temperature_c", value: float = 95.0) -> AttackResult:
        """Authenticated telemetry with a value outside the device's expected range (twin / trust config)."""
        agent = self._need_agent()

        def act():
            r = agent.telemetry(**{field_name: value})
            return [r.status_code], {field_name: value}
        return self._run("abnormal_sensor_telemetry", "HTTP 200 (authentic); sensor_out_of_range penalty (requires a "
                         "configured range)", act, lambda ev, b, a: (a.get("factors", {}).get("sensor_consistency", {})
                                                                      .get("penalty") or 0) > 0)

    def tamper(self) -> AttackResult:
        """The device reports its enclosure tamper switch open (SIMULATED: software agent, no real switch)."""
        agent = self._need_agent()

        def act():
            r = agent.telemetry(tamper=True)
            return [r.status_code], {"tamper": True}
        return self._run("physical_tamper", "HTTP 200; physical_tamper penalty; cap physical_tamper (55)", act,
                         lambda ev, b, a: a.get("tamper_active") is True)

    def config_mismatch(self, cfg_hash: str = "cfg-tampered-0000") -> AttackResult:
        """The device reports a configuration hash different from its expected (twin) state."""
        agent = self._need_agent()

        def act():
            r = agent.telemetry(cfg_hash=cfg_hash)
            return [r.status_code], {"cfg_hash": cfg_hash}
        return self._run("config_integrity_mismatch", "HTTP 200; integrity_mismatch penalty; cap integrity_mismatch (65)",
                         act, lambda ev, b, a: "integrity_mismatch" in [c["name"] for c in a.get("caps", [])])

    def visual_violation(self, confidence: float = 0.9) -> AttackResult:
        """A signed detection matching the restricted-zone rule (synthetic detection, real ML-DSA signature)."""
        def act():
            env = self._signed(self._obs(anomaly=True, confidence=confidence))
            r = self.gw.post("/api/v1/observations/signed", json=env)
            return [r.status_code], {"confidence": confidence, "observation_id": env["observation_id"]}
        return self._run("visual_rule_violation", "HTTP 200; visual penalty 100*c^2", act,
                         lambda ev, b, a: (a.get("factors", {}).get("visual", {}).get("penalty") or 0) > 0)

    def correlated(self, confidence: float = 0.9) -> AttackResult:
        """Tamper report corroborated by a signed visual violation within the correlation window."""
        agent = self._need_agent()

        def act():
            r1 = agent.telemetry(tamper=True)
            env = self._signed(self._obs(anomaly=True, confidence=confidence))
            r2 = self.gw.post("/api/v1/observations/signed", json=env)
            return [r1.status_code, r2.status_code], {"tamper": True, "visual_confidence": confidence}
        return self._run("correlated_multi_signal", "confirmed_incident (cap 30) -> QUARANTINED; normal access blocked",
                         act, lambda ev, b, a: a.get("state") == "QUARANTINED")

    def quarantine_bypass(self) -> AttackResult:
        """While quarantined: (a) the device's own normal telemetry, (b) forged 'all clear' telemetry."""
        agent = self._need_agent()

        def act():
            r1 = agent.telemetry(tamper=False)
            env = build_hmac_envelope(secrets.token_bytes(32), MSG_TELEMETRY, self.device_id, 10**13,
                                      json.dumps({"tamper": False}))
            r2 = self.gw.post("/api/v1/telemetry", json=env)
            return [r1.status_code, r2.status_code], {"attempt": "normal channel while quarantined + forged all-clear"}
        return self._run("quarantine_bypass", "authentic normal telemetry 403 (quarantine_access_blocked); forged 401; "
                         "state stays QUARANTINED", act,
                         lambda ev, b, a: self._has(ev, "quarantine_access_blocked") and a.get("state") == "QUARANTINED")

    # ------------------------------------------------------------------ report
    def summary(self) -> list[dict]:
        return [{"attack": r.attack_type, "http": r.http_status, "detected": r.detected,
                 "score": f"{r.trust_effect['before']} -> {r.trust_effect['after']}",
                 "state": f"{r.state_effect['before']} -> {r.state_effect['after']}", "evidence_id": r.evidence_id}
                for r in self.results]

